### PR TITLE
Change layout and theme

### PR DESCRIPTION
**Pull request by ethsdev**
I have changed layout as side bar menu and theme of black and white color.

### CODE REVIEW

**Comment by crazydevlegend** [comment]
left review on vercel preview, need more changes with the theme

**Comment by crazydevlegend** [comment]
nice job, we're close, plz check my feedback on vercel

**Comment by crazydevlegend** [comment]
page is not responsive yet - plz fix and then lets merge this PR @solthereum

**Comment by ethsdev** [comment]
okay, I will fix it more

**Review by crazydevlegend — APPROVED** [review]
lgtm

**Pull request merged**
